import { z } from 'zod';
import {
  zAlert,
  zEnvelope,
  zKpi,
  zMachineStatus,
  zPolicyBlock,
  zProcess,
  zRange,
  zShift,
  zStatusBucket,
  zTrendPoint,
} from './common.ts';
import { zIanaTz, zIsoUtc, zPct, zQty } from './primitives.ts';
import { zPlantSummary } from './globalOverview.ts';
import { zZoneSummary } from './companyDetail.ts';

/**
 * `GET /api/v1/companies/{company}/plants/{plant}?range=&process=&shift=`
 *
 * The machine-level view that replaces the Machine Status V2.0 Grafana panel.
 */

/** One production-order slot. The IO measurement carries four per machine. */
export const zPoSlot = z.object({
  slot: z.number().int().min(0).max(3),
  production_order: z.string(),
  part_no: z.string().nullable(),
  part_name: z.string().nullable(),
  plan_qty: zQty,
  created_at: zIsoUtc.nullable(),
});
export type PoSlot = z.infer<typeof zPoSlot>;

export const zMachine = z.object({
  id: z.string(), // 'I1' | 'P2I1'
  zone: z.string().nullable(),
  process: zProcess.nullable(),
  status: zMachineStatus,
  /**
   * Which bucket this status belongs in. Sent by the backend so D-21 - is
   * `4M Change` running or stopped? - is decided once, server-side, and the UI
   * only picks a colour and a glyph. When the decision lands it is an enum move
   * in one place with no front-end change at all.
   */
  bucket: zStatusBucket,
  status_since: zIsoUtc.nullable(),
  mode: z.enum(['Auto', 'Manual']).nullable(),

  oa_pct: zPct,
  oa_tier: zKpi.shape.oa_tier,
  achievement_pct: zPct,
  plan_qty: zQty,
  /** Section 8.5: pieces (SUM qty) and shots (COUNT cavity) are separate facts. */
  actual_qty: zQty,
  shot_count: zQty,

  po_slots: z.array(zPoSlot),

  std_time_sec: z.number().nullable(),
  cycle_time_sec: z.number().nullable(),
  avg_cycle_time_sec: z.number().nullable(),
  /** Section 8.3 timing detail. Collapsed behind an accordion - too dense for a card face. */
  time_mold_opening_sec: z.number().nullable(),
  time_mold_end_sec: z.number().nullable(),
  time_injection_sec: z.number().nullable(),

  last_seen: zIsoUtc.nullable(),
  grafana_url: z.string().nullable(),
});
export type Machine = z.infer<typeof zMachine>;

/**
 * One column of the hourly output table.
 *
 * This is the shape that makes section 9.5's 22:15 problem disappear from the
 * front end entirely. The old UI hardcodes twelve `08:00 - 09:00` columns, which
 * is wrong for STJ in two separate ways: its A shift has eight, and its B shift
 * ends at 22:15 so the last column covers fifteen minutes, not sixty.
 *
 * `duration_min` is therefore mandatory and must never be assumed to be 60. The
 * table sizes each column proportionally to it, otherwise a 15-minute bucket
 * reads as a catastrophic collapse in output.
 *
 * `qty_per_hour` is the only figure that is comparable across unequal buckets,
 * and it is computed server-side like everything else.
 */
export const zOutputBucket = z.object({
  index: z.number().int().positive(),
  label: z.string(), // '22:00-22:15' - generated by the backend from shift config
  start_utc: zIsoUtc,
  end_utc: zIsoUtc,
  duration_min: z.number().positive(),
  is_partial: z.boolean(),
  state: z.enum(['complete', 'in_progress', 'not_started', 'break']),
  qty_pcs: zQty,
  qty_shots: zQty,
  plan_qty: zQty,
  qty_per_hour: zQty,
  oa_pct: zPct,
});
export type OutputBucket = z.infer<typeof zOutputBucket>;

export const zShiftOutput = z.object({
  shift_code: z.string(),
  shift_label: z.string(),
  buckets: z.array(zOutputBucket),
});
export type ShiftOutput = z.infer<typeof zShiftOutput>;

export const zPlantDetail = zPolicyBlock.extend({
  meta: zEnvelope,
  filters_applied: z.object({
    range: zRange,
    process: z.union([zProcess, z.literal('all')]),
    shift: z.string(), // 'current' | a shift code
  }),
  company: z.object({
    code: z.string(),
    name: z.string(),
    name_th: z.string().nullable(),
    country_code: z.string().length(2),
    timezone: zIanaTz,
  }),
  plant: zPlantSummary,
  shift: zShift.nullable(),
  zones: z.array(zZoneSummary),
  machines: z.array(zMachine),
  output: zShiftOutput.nullable(),
  trend: z.array(zTrendPoint),
  alerts: z.array(zAlert),
});
export type PlantDetail = z.infer<typeof zPlantDetail>;
